CREATE TABLE users (
  id SERIAL PRIMARY KEY,
  name VARCHAR NOT NULL,
  email TEXT NOT NULL,
  role VARCHAR NOT NULL DEFAULT 'USER',
  password bytea NOT NULL,
  active BOOLEAN NOT NULL DEFAULT FALSE
);
